#!/bin/sh
#
# Create QMailToaster yum repository mirror.list files
#
# This should perhaps be a php script some day.
# It would need to be in all mirrors though, which could be problematic.
#####################################################################
# change log
# 11/25/13 shubes - created
#####################################################################

mirrors="1 2 3 4 5 6 8"

#####################################################################
#
a5_each_status(){

basedir=/repos/$status

for distrodir in $(find $basedir -mindepth 1 -maxdepth 1 -type d); do
  distro=${distrodir##*/}
  case $distro in
    SRPMS )
      :
      ;;
    nodist )
      q51_create_mirror_file ''
      ;;
    * )
      q51_create_mirror_file '/$releasever/$basearch'
      ;;
  esac
done
}

#####################################################################
## create a mirror.list file
#
q51_create_mirror_file(){

mirrorfile=$basedir/$distro/mirror.list
echo "$me - creating $mirrorfile ..."
rm -f $mirrorfile

for mirror in $mirrors; do
  echo "http://mirror$mirror.qmailtoaster.com/$status/$distro$1" >>$mirrorfile
done
}

#####################################################################
## begin main processing here
#
me=${0##*/}
myver=v1.0
echo "$me $myver"

for status in current testing devel; do
  a5_each_status
done

echo "$me - done"
exit 0
