#!/bin/sh
#
# Create/update QMailToaster yum repositories
#####################################################################
# change log
# 11/24/13 shubes - migrated from qmailtoaster-plus to QMailToaster
# 08/22/09 shubes - created
#####################################################################
#
a5_each_status(){

basedir=/repos/$status

echo "$me - processing $basedir/nodist"
createrepo -p $basedir/nodist

for distrel in $distrel_list; do
  for repodir in $(find $basedir/$distrel -mindepth 1 -maxdepth 1 -type d); do
    echo "$me - processing $repodir"
    createrepo -p $repodir
  done
done
}

#####################################################################
## begin main processing here
#
me=${0##*/}
myver=v1.0
echo "$me $myver"

distrel_list="\
centos/5 \
centos/6 \
"

for status in current testing devel; do
  a5_each_status
done

echo "$me - done"
exit 0
